issues:
  exclude-rules:
    - path: buildkite/agent.go
      linters:
        # type assertion does not need checking as this will run in linux only (via Docker)
        - forcetypeassert

linters:
  enable-all: true
  disable:
    - asciicheck
    - depguard
    - dupl
    - err113
    - errname
    - exhaustruct
    - exportloopref
    - forbidigo
    - funlen
    - gci
    - gochecknoglobals
    - gocognit
    - goconst
    - godot
    - godox
    - gofumpt
    - lll
    - nestif
    - nilnil
    - nlreturn
    - paralleltest
    - prealloc
    - revive
    - tagliatelle
    - testpackage
    - unparam
    - varnamelen
    - wrapcheck
    - wsl

linters-settings:
  gosec:
    # all rules enabled
    # see also: https://securego.io/docs/rules/rule-intro.html
    config:
      global:
        # allow #nosec override comments
        nosec: enabled
        # disable potentially noisy stricter audit mode
        audit: disabled
      G101: # "Look for hard-coded credentials"
        mode: strict
  cyclop:
    max-complexity: 20
